name: Benchmark
on:
  push:
    branches: 
      - main

jobs:
  benchmark:
    name: Check performance 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Run benchmark 
        run: npm install && npm run bench | tee output.txt
      - name: Store benchmark result 
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Benchmark.js Benchmark 
          tool: 'benchmarkjs'
          output-file-path: output.txt 
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '130%'
          comment on alert: true 
          fall-on-alert: true
          alert-comment-cc-users: '@acolmena'
